# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f0fe45cdc34b9802e5e76640db2b1d6ab13444de160f8540da1e491bbf38a3fea0aab424958e1fec63c9ef93510b8c20db6d6ec053aca64a194ddf6461d4ad3c

test:
  secret_key_base: f412f9d7e0195a109d5e4a4bf94b42ea3aefcacecad53956a6463fe85996e300196d176be580dea2306cf69d10b68d9776786483b801ffe253972621f434d7fc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
